apiVersion: apps/v1
kind: Deployment
metadata:
  name: uc-fe
  namespace: ctg-hr-dev
  labels:
    app: uc-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uc-fe
  template:
    metadata:
      labels:
        app: uc-fe
    spec:
      imagePullSecrets:
        - name: harbor
      containers:
        - name: uc-fe
          image: harbor.evescn.com/ctg-hr/uc-fe:latest
          imagePullPolicy: Always
          env:
            - name: "TZ"
              value: "Asia/Shanghai"
            - name: "API_HOST"
              value: "microservices-gateway.ctg-hr-dev:8080"
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
          resources:
            limits:
              cpu: "1.0"
              memory: 512Mi
            requests:
              cpu: "0.5"
              memory: 128Mi
